"use client";

import React, { useState, useEffect } from "react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import {
  FileText,
  TrendingUp,
  TrendingDown,
  Calendar,
  Award,
  BookOpen,
  UserCheck,
} from "lucide-react";

interface StudentReport {
  id: string;
  attendanceSummary: string;
  performanceScore: number;
  trendAnalysis: string;
  aiRecommendation: string;
  isSent: boolean;
  generatedAt: string;
}

export default function StudentParentReportsPage() {
  const [reports, setReports] = useState<StudentReport[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchMyReports = async () => {
      try {
        const response = await api.get(`/parent-reports/me`);
        if (response.data && response.data.success) {
          setReports(response.data.data);
        }
      } catch (err: any) {
        console.error("Failed to load reports:", err);
        setError("Failed to retrieve academic report cards.");
      } finally {
        setLoading(false);
      }
    };

    fetchMyReports();
  }, []);

  const getPerformanceLevel = (score: number) => {
    if (score >= 75) return { label: "Excellent", color: "bg-emerald-50 text-emerald-700 border-emerald-200" };
    if (score >= 60) return { label: "Good", color: "bg-blue-50 text-blue-700 border-blue-200" };
    if (score >= 45) return { label: "Average", color: "bg-amber-50 text-amber-700 border-amber-200" };
    return { label: "At Risk", color: "bg-red-50 text-red-700 border-red-200" };
  };

  const getTrendBadge = (trend: string) => {
    switch (trend) {
      case "IMPROVING":
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
            <TrendingUp className="w-3.5 h-3.5" /> Improving
          </span>
        );
      case "DECLINING":
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-red-50 text-red-700 border border-red-200">
            <TrendingDown className="w-3.5 h-3.5" /> Declining
          </span>
        );
      default:
        return (
          <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-blue-50 text-blue-700 border border-blue-200">
            Stable
          </span>
        );
    }
  };

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  return (
    <div className="p-6 space-y-6 max-w-5xl mx-auto min-h-screen">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-extrabold text-foreground tracking-tight">My Academic Reports</h1>
        <p className="text-muted-foreground mt-1">
          Review your monthly performance metrics and personalized recommendations.
        </p>
      </div>

      {loading ? (
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, idx) => (
            <Card key={idx} className="p-5 animate-pulse border-border">
              <div className="h-6 bg-muted rounded-md w-1/4 mb-4"></div>
              <div className="h-4 bg-muted rounded-md w-3/4 mb-2"></div>
              <div className="h-4 bg-muted rounded-md w-1/2"></div>
            </Card>
          ))}
        </div>
      ) : error ? (
        <Card className="p-6 text-center border-border bg-card">
          <p className="text-red-600 font-semibold">{error}</p>
        </Card>
      ) : reports.length === 0 ? (
        <Card className="p-12 text-center border-border bg-card">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <h3 className="text-lg font-bold text-foreground mb-2">No Reports Available</h3>
          <p className="text-muted-foreground max-w-sm mx-auto">
            Your monthly performance report card will appear here once it is generated by the administrator.
          </p>
        </Card>
      ) : (
        <div className="space-y-6">
          {reports.map((report) => {
            const date = new Date(report.generatedAt);
            const formattedDate = date.toLocaleDateString("en-US", {
              month: "long",
              year: "numeric",
            });
            const level = getPerformanceLevel(report.performanceScore);

            return (
              <Card key={report.id} className="p-6 border-border bg-card shadow-sm hover:shadow-md transition-shadow">
                {/* Top Section */}
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-5 pb-4 border-b border-border">
                  <div className="flex items-center gap-3">
                    <Calendar className="w-5 h-5 text-emerald-600" />
                    <h3 className="text-lg font-bold text-foreground">{formattedDate} Report Card</h3>
                  </div>
                  <div className="flex items-center gap-2">
                    {getTrendBadge(report.trendAnalysis)}
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold border ${level.color}`}>
                      {level.label}
                    </span>
                  </div>
                </div>

                {/* Score Breakdown Cards */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                  <div className="bg-muted/20 p-4 rounded-xl border border-border flex items-center gap-3">
                    <UserCheck className="w-5 h-5 text-emerald-600" />
                    <div>
                      <span className="text-[11px] text-muted-foreground font-semibold block uppercase">Attendance</span>
                      <p className="text-base font-bold text-foreground mt-0.5">
                        {report.attendanceSummary.match(/Attendance: (\d+)%/)?.[1] || "0"}%
                      </p>
                    </div>
                  </div>

                  <div className="bg-muted/20 p-4 rounded-xl border border-border flex items-center gap-3">
                    <BookOpen className="w-5 h-5 text-blue-600" />
                    <div>
                      <span className="text-[11px] text-muted-foreground font-semibold block uppercase">Quiz Avg</span>
                      <p className="text-base font-bold text-foreground mt-0.5">
                        {report.attendanceSummary.match(/Quiz: (\d+)%/)?.[1] || "0"}%
                      </p>
                    </div>
                  </div>

                  <div className="bg-muted/20 p-4 rounded-xl border border-border flex items-center gap-3">
                    <FileText className="w-5 h-5 text-purple-600" />
                    <div>
                      <span className="text-[11px] text-muted-foreground font-semibold block uppercase">Assignment</span>
                      <p className="text-base font-bold text-foreground mt-0.5">
                        {report.attendanceSummary.match(/Assignment: (\d+)%/)?.[1] || "0"}%
                      </p>
                    </div>
                  </div>

                  <div className="bg-muted/20 p-4 rounded-xl border border-border flex items-center gap-3">
                    <Award className="w-5 h-5 text-amber-600" />
                    <div>
                      <span className="text-[11px] text-muted-foreground font-semibold block uppercase">Weighted Score</span>
                      <p className="text-base font-bold text-emerald-600 mt-0.5">{report.performanceScore.toFixed(1)}%</p>
                    </div>
                  </div>
                </div>

                {/* Recommendation */}
                <div className="bg-emerald-500/5 border border-emerald-500/10 p-4 rounded-xl">
                  <h4 className="text-xs font-bold text-emerald-800 dark:text-emerald-300 uppercase tracking-wider mb-1.5">
                    Counselor Recommendation
                  </h4>
                  <p className="text-sm text-emerald-950 dark:text-emerald-300 italic">
                    "{report.aiRecommendation}"
                  </p>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
