import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  scrollContent: {
    paddingBottom: 100, // Space for bottom nav
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 20,
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 140,
    height: 30,
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  profilePic: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#EEF2FF",
  },
  greetingSection: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  greetingTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#0F172A",
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  greetingSubtitle: {
    fontSize: 14,
    color: "#475569",
  },
  quickActionsScroll: {
    paddingHorizontal: 24,
    marginBottom: 32,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 99,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  actionButtonText: {
    color: "#0F172A",
    fontWeight: "700",
    marginLeft: 8,
    fontSize: 14,
  },
  section: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitleText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#1B4FCC",
    textTransform: "uppercase",
  },
  glassCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    overflow: "hidden",
  },
  attendanceCard: {
    alignItems: "center",
    paddingVertical: 32,
  },
  progressCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 8,
    borderColor: "#EEF2FF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#1B4FCC",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 5,
  },
  progressText: {
    fontSize: 32,
    fontWeight: "900",
    color: "#1B4FCC",
  },
  attendanceTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  attendanceStandard: {
    fontSize: 10,
    fontWeight: "800",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  performanceCard: {
    padding: 24,
  },
  performanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  performanceTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 4,
  },
  performanceStat: {
    fontSize: 14,
    fontWeight: "700",
    color: "#10B981",
  },
  chartPlaceholder: {
    height: 60,
    width: "100%",
    justifyContent: "center",
  },
  nextClassCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
  },
  iconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#EEF2FF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  nextClassInfo: {
    flex: 1,
  },
  nextClassLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 2,
  },
  nextClassSubject: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  nextClassTimeBox: {
    alignItems: "flex-end",
  },
  nextClassTime: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1B4FCC",
    marginBottom: 2,
  },
  nextClassCountdown: {
    fontSize: 12,
    color: "#475569",
  },
  aiInsightCard: {
    padding: 24,
    backgroundColor: "#EEF2FF",
    borderColor: "#4A78E8",
    borderWidth: 1,
    shadowColor: "#1B4FCC",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 3,
  },
  aiInsightHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  aiInsightTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
    marginLeft: 12,
  },
  aiInsightText: {
    fontSize: 14,
    color: "#475569",
    lineHeight: 22,
    marginBottom: 20,
  },
  aiInsightHighlight: {
    fontWeight: "800",
    color: "#1B4FCC",
  },
  aiInsightButton: {
    backgroundColor: "#1B4FCC",
    paddingVertical: 14,
    borderRadius: 99,
    alignItems: "center",
  },
  aiInsightButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  materialsScroll: {
    paddingHorizontal: 24,
  },
  materialCard: {
    width: 160,
    marginRight: 16,
  },
  materialImage: {
    width: 160,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#F1F5F9",
    marginBottom: 12,
  },
  materialTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 4,
  },
  materialMeta: {
    fontSize: 12,
    color: "#94A3B8",
  },
  bottomNavContainer: {
    position: "absolute",
    bottom: 24,
    left: 24,
    right: 24,
    height: 64,
    borderRadius: 32,
    overflow: "hidden",
  },
  bottomNavBlur: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 32,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
  },
  navItemActive: {
    backgroundColor: "rgba(29, 185, 84, 0.1)",
    borderRadius: 24,
  },
});
